module.exports = {
    JWT_SECRET: process.env.JWT_SECRET || '$2bJpYXQiOjE2MTYxNDE3NTQsImV4cCI6MTYxNjE0MjA1NH0',
    JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET || '$2bJpYXQiOjE2QsImV4cCI6MTYxNjE0MjA1NH0',
    JWT_ACTIVATE_SECRET: process.env.JWT_REFRESH_SECRET || '$2b$10$F6x7rYybJpYXQiOjE2MTYxNDE3NTQsImV4cCI6MTYxNjE0MjA1NH0'
};
